package com.xianyu.chuhuomingxi.mapper;

import com.xianyu.chuhuomingxi.entity.GongyingshangDizhi;
import java.util.List;

public interface GongyingshangDizhiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongyingshang_dizhi
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongyingshang_dizhi
     *
     * @mbg.generated
     */
    int insert(GongyingshangDizhi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongyingshang_dizhi
     *
     * @mbg.generated
     */
    GongyingshangDizhi selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongyingshang_dizhi
     *
     * @mbg.generated
     */
    List<GongyingshangDizhi> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongyingshang_dizhi
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GongyingshangDizhi record);
}