package com.xianyu.chuhuomingxi.mapper;

import com.xianyu.chuhuomingxi.entity.JinghuoDetail;
import java.util.List;

public interface JinghuoDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinghuo_Detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinghuo_Detail
     *
     * @mbg.generated
     */
    int insert(JinghuoDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinghuo_Detail
     *
     * @mbg.generated
     */
    JinghuoDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinghuo_Detail
     *
     * @mbg.generated
     */
    List<JinghuoDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinghuo_Detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JinghuoDetail record);
}