package com.xianyu.chuhuomingxi.mapper;

import com.xianyu.chuhuomingxi.entity.TuihuoDetail;
import java.util.List;

public interface TuihuoDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuihuo_Detail
     *
     * @mbg.generated
     */
    int insert(TuihuoDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuihuo_Detail
     *
     * @mbg.generated
     */
    List<TuihuoDetail> selectAll();
}