package com.xianyu.chuhuomingxi.mapper;

import com.xianyu.chuhuomingxi.entity.Xianyumaster;
import java.util.List;

public interface XianyumasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xianyuMaster
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xianyuMaster
     *
     * @mbg.generated
     */
    int insert(Xianyumaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xianyuMaster
     *
     * @mbg.generated
     */
    Xianyumaster selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xianyuMaster
     *
     * @mbg.generated
     */
    List<Xianyumaster> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xianyuMaster
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Xianyumaster record);
}